### ISSUE TITLE
App doesnt compile

### ISSUE THREAD

**Issue by humarkx** [anthonyraymond/joal-desktop#37]
OS: Mac Big Sur
Joal App version: 2.0.6

https://prntscr.com/w05t04

**Comment by theofruitrouge** [comment]
I have the same issue.
OS : Catalina (current version)
Joal : current

**Comment by anthonyraymond** [comment]
If you refer to the red cross it's normal, on mac i can't auto update due to apple's shitty policy, this is the reason for the red cross.

Also on mac it seems that the pac is doing shaggy think in the backgroud... I took a looooooot of time to first start the first time. Further start seems tonbe muxh more quicker.
Wait for 5 to 10 min on this screen.

**Comment by humarkx** [comment]
> If you refer to the red cross it's normal, on mac i can't auto update due to apple's shitty policy, this is the reason for the red cross.
> 
> Also on mac it seems that the pac is doing shaggy think in the backgroud... I took a looooooot of time to first start the first time. Further start seems tonbe muxh more quicker.
> Wait for 5 to 10 min on this screen.

I will open and wait 5 to 10 min

**Comment by humarkx** [comment]
It is open for some time, doesn't compile

**Comment by anthonyraymond** [comment]
Can you close Joal (i mean exit completly, don't leave it in the app bar at the bottom) and try this solution: https://github.com/anthonyraymond/joal-desktop/issues/13#issuecomment-556944021

the 5081 remains the same but you'll need to adapt the **353571** according to the *lsof* result

**Comment by humarkx** [comment]
That worked

**Comment by anthonyraymond** [comment]
Great :)
