### ISSUE TITLE
Torrents randomly & unexpectedly disappeared

### ISSUE THREAD

**Issue by xizhengszhang** [anthonyraymond/joal-desktop#8]
## Context
User tries to make announcements to tracker for each of 100 torrents at least once per hour to earn bonus points.
However, torrents randomly & unexpectedly disappeared after some periods of time, forcing the user to check the UI and add missing torrents back manually from time to time to maintain maximum throughput.

## Environment
OS: macOS 10.14.5
joal-desktop Version: 2.0.0

## Steps to Reproduce
1. Open JOAL ui, go to configuration tab, 
2. Set "Min upload rate (kB/s)" to 0, set "Max upload rate (kB/s)" to 0, set "Torrent client" to "transmission-2.94", set "Simultaneous seed" to 100, check "Keep seeding torrents even with no peers". Click save.
3. Go to dashboard tab, click STOP, quit JOAL ui, open JOAL ui
4. Click "Add a torrent", select 100 private torrent files, click open
5. Open Terminal, run caffeinate
6. Let the computer run for 2 days

## Expected Behavior
After 2 days, there are 100 torrents in dashboard tab.

## Current Behavior
After 2 days, there are 97 torrents in dashboard tab.

**Comment by anthonyraymond** [comment]
Hi :)

Thanks for reporting this. Thanks a lot for all these details, it's pretty rare when people explain their problem that well 😃 

Since it does not seems related to a network issue (because 97 are still there) we'll need to investigate a bit more.

**Here is what you'll need to do**:
1) Close JoalDesktop completly.
2) Head to [this page](https://github.com/anthonyraymond/joal-desktop/blob/master/debug-scripts/joal-desktop-debug.macos.sh) and copy the whole script into a file named `debug-joal.sh`. Put this file whereever you want but remember where it is.
3) Open a terminal and `cd` to the folder where you've put the file `debug-joal.sh`.
4) Run the following command : `sh ./debug-joal.sh > joal.log`

**Things to known**:
- You won't see nothing in the terminal because the output will be redirected to the `joal.log` file.
- If you want to stop the joal script you can press `CMD+C` or `CTRL+C` i don't known which one on macOs.
- When the script is running (+-20 sec after the scritp started up) your Joal User Interface will be available at [this page](http://localhost:5081/aaaaa/ui/), in the top left corner you'll see a red button that asks you how to connect to joal. Fill it with the following:
![image](https://user-images.githubusercontent.com/7503585/59535090-499f9080-8ef0-11e9-89b7-38765506f924.png)
- If the webui is not working trhough the previous link there is probably something that has messed up and joal is probably not running properly. There is no need to let the script for two days, we need to get it working.




**What to do next**
1) Add your 100 torrents (the one you had in joal-desktop will probably be here already).
2) Let the script run till you see missing torrents in the User Interface.
3) Stop the script.
4) Send me the log at `joal.contact@gmail.com` and and a link to this issue so i known that it's related to this one :). **DO NOT POST THE LOG HERE, it contains your IP, passkey and so on**

**Comment by xizhengszhang** [comment]
Thank you a lot. I have let the computer run for 3 days, and I cannot reproduce this issue again, using the provided script. I will let it run for the next week, and see if I can find anything. I will also try to not use the script, and see if that will make any difference.

**Comment by anthonyraymond** [comment]
alright ;)

**Comment by xizhengszhang** [comment]
Thank you Anthony for giving attention to this issue, but after 7 days, I still cannot reproduce this "bug". I suggest close this issue.

**Comment by anthonyraymond** [comment]
Ok, keep in mind that this problem may occur when you drop connections or when the tracker offline. Joal automatically remove torrent when he can't annouce to the tracker.
But you are most likely to loose them all at a time, not juste 3 of them. Let me know if you still encouter this issue later on
